sources:
  - pacman
  - scoop
  - brew
  - aur
  - cargo
  - apt
  - nix
packages:
  - bat
  - bottom
  - chezmoi
  - direnv
  - dust
  - exa
  - fd
  - fnm
  - fzf
  - gh
  - ghq
  - git-delta
  - gitui
  - golang
  - grex
  - hub
  - jq
  - lsd
  - mc
  - micro
  - nnn
  - pueue
  - procs
  - pyenv
  - python
  - rg
  - rustup
  - sd
  - tealdeer
  - thefuck
  - tmux
  - viu
  - wget:apt
  - zellij
  - zoxide
  -
