#!/bin/bash
# Santa Package Manager Installation Script
# Generated: 2026-03-28T03:12:40.587917989+00:00
# Version: 0.3.3
# Source: brew
# Packages: 3

set -euo pipefail

echo "🎅 Santa Package Installation - brew"
echo "Generated: 2026-03-28T03:12:40.587917989+00:00"
echo "Packages to install: 3"
echo ""


# Homebrew package installation
if command -v brew &> /dev/null; then
    echo "📦 Installing Homebrew packages..."
    
    echo "Installing direnv..."
    brew install direnv
    
    echo "Installing github-cli..."
    brew install github-cli
    
    echo "Installing nnn..."
    brew install nnn
    
    echo "✅ Homebrew installation completed"
else
    echo "⚠️  Homebrew not found. Please install Homebrew first:"
    echo "   /bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
    echo "   Then run this script again."
    exit 1
fi



echo ""
echo "🎉 All 3 packages have been processed!"
echo "Generated by Santa v0.3.3 - https://github.com/tylerbutler/santa"