name: 'Install Cargo Tools'
description: 'Install common development tools used across workflows'

inputs:
  tools:
    description: 'Comma-separated list of tools to install'
    required: true
    default: 'just'

runs:
  using: composite
  steps:
    - name: Install Tools
      uses: tylerbutler/actions/install-tools@main
      with:
        tools: ${{ inputs.tools }}
