//! Serde with CCL: reading typed values, writing them back, and keeping
//! comments across a read-modify-write cycle.
//!
//! Run with: `cargo run -p sickle --example serde_usage --features serde`

use serde::{Deserialize, Serialize};
use sickle::{BoolBehavior, DocumentMut, Options};

#[derive(Debug, Serialize, Deserialize, PartialEq)]
struct Server {
    host: String,
    port: u16,
}

#[derive(Debug, Serialize, Deserialize, PartialEq)]
struct Config {
    name: String,
    server: Server,
    hosts: Vec<String>,
    enabled: bool,
}

const SOURCE: &str = "\
/= Generated by the installer — edit freely
name = gateway
server =
  host = 0.0.0.0
  port = 8080
hosts =
  = api-1
  = api-2
enabled = true
";

fn main() {
    // Deserialize straight from text.
    let config: Config = sickle::de::from_str(SOURCE).unwrap();
    println!("{config:#?}");

    // Serialize back to canonical CCL. This produces new text, so the source
    // comments are not part of it.
    let rendered = sickle::ser::to_string(&config).unwrap();
    println!("--- canonical ---\n{rendered}\n");
    assert!(!rendered.contains("/="));

    // To keep the comments, parse the document once and write the values you
    // changed back through the checked editing API.
    let mut doc: DocumentMut = SOURCE.parse().unwrap();
    let mut config: Config = sickle::de::from_document(&doc).unwrap();

    config.server.port = 9090;
    config.hosts.push("api-3".into());

    doc.set_int(["server", "port"], config.server.port.into())
        .unwrap();
    doc.set_list(["hosts"], config.hosts.clone()).unwrap();

    println!("--- edited in place ---\n{doc}");
    assert!(doc.to_string().starts_with("/= Generated by the installer"));

    // Behavior options apply to Serde too.
    #[derive(Deserialize)]
    struct Flag {
        enabled: bool,
    }
    let lenient = Options::new().with_bool(BoolBehavior::Lenient);
    let flag: Flag = sickle::de::from_str_with("enabled = yes\n", &lenient).unwrap();
    println!("lenient bool = {}", flag.enabled);
}
